apiVersion: v1
kind: ServiceAccount
metadata:
  name: danm-cleaner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:danm-cleaner
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - get
- apiGroups:
  - danm.k8s.io
  resources:
  - danmnets
  - danmeps
  - tenantnetworks
  - clusternetworks
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:danm-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:danm-cleaner
subjects:
- kind: ServiceAccount
  name: danm-cleaner
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: danm-cleaner
  namespace: kube-system
  labels:
    danm: cleaner
spec:
  selector:
    matchLabels:
     danm: cleaner
  template:
    metadata:
      name: danm-cleaner
      labels:
        danm: cleaner
    spec:
      serviceAccountName: danm-cleaner
      containers:
        - name: danm-cleaner
          image: cleaner
         imagePullPolicy: IfNotPresent
